### PR TITLE
internal/dag: allow valid cross-namespace Gateway TLS cert refs

### LINKED ISSUE #4181: Gateway API: Cross namespace TLS certificateRefs does not work
**What steps did you take and what happened:**

- As per [Cross namespace certificate references](https://gateway-api.sigs.k8s.io/v1alpha2/guides/tls/#cross-namespace-certificate-references), Gateway should support cross namespace certificate.
- But contour always looks for the secret in the Gateway namespace as per the following code `Namespace: p.source.gateway.Namespace`:

https://github.com/projectcontour/contour/blob/941d33738949e231005cc2167547d654e3b98a52/internal/dag/gatewayapi_processor.go#L271

**What did you expect to happen:**

- [Cross namespace certificate references](https://gateway-api.sigs.k8s.io/v1alpha2/guides/tls/#cross-namespace-certificate-references) should work as per Gateway API doc.

**Environment:**

Contour installed via the yaml (2021/Nov/15):

```
CONTOUR_OPERATOR_VERSION="main" # This is for controlling which version of contour-operator we want to use.
YAML_URL="https://raw.githubusercontent.com/projectcontour/contour-operator/${CONTOUR_OPERATOR_VERSION}/examples/operator/operator.yaml"
```
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-19T11:52:07Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T20:01:24Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
```

### PR DESCRIPTION
**Pull request by skriss**
Allows Gateways to reference TLS certificates in
other namespaces when a corresponding ReferencePolicy
exists.

Closes #4181.

Signed-off-by: Steve Kriss <krisss@vmware.com>

### CODE REVIEW

File: internal/dag/gatewayapi_processor.go [hunk 1]
```diff
@@ -366,6 +401,60 @@ func (p *GatewayAPIProcessor) validGatewayTLS(listenerTLS gatewayapi_v1alpha2.Ga
...
+			}
+		}
+		if !fromAllowed {
+			continue
+		}
+
+		// Check if the ReferencePolicy has a matching "to".
+		var toAllowed bool
+		for _, refPolicyTo := range referencePolicy.Spec.To {
+			if string(refPolicyTo.Group) == to.group && string(refPolicyTo.Kind) == to.kind && (refPolicyTo.Name == nil || *refPolicyTo.Name == "" || string(*refPolicyTo.Name) == to.name) {
```
Comment (sunjayBhatia) [inline internal/dag/gatewayapi_processor.go:440]: is it valid for someone to put `core` as the group for a secret rather than empty? only edge case I can think of since we're checking for equality of the group

**Review by sunjayBhatia — APPROVED** [review]
LGTM

one minor edge case question but looks great! nice refactor with the helper 👍🏽

**Review by stevesloka — APPROVED** [review]

File: internal/dag/gatewayapi_processor.go (hunk 1 above)
Comment (skriss) [reply internal/dag/gatewayapi_processor.go:440]: Good question -- I have another change lined up to drop "core" as a magic string for the core group from the rest of the Gateway API implementation, since it's not mentioned in the Gateway API spec anywhere, and everything indicates "" should be used to refer to the core API group. Decided not to add support for it here and then immediately drop it.
