### PR TITLE
Use polling during startup to wait for informers to sync

### LINKED ISSUE #6613: Contour occasionally gets stuck in a non-ready state and fails to start the XDS server
Contour occasionally gets stuck in a non-ready state and fails to start the XDS server. This issue is uncommon and occurs only under the following conditions:

* `--watch-namespaces` flag is set to monitor a single namespace.
* That namespace has only "unrelated" secrets that Contour does not process.
* The stuck Contour instance is the follower (not leader).

To reproduce this issue, follow these steps:

1. Deploy contour:

```bash
$ kubectl apply -f https://projectcontour.io/quickstart/contour.yaml
```

2. Create a nearly empty namespace with one generic secret:

```bash
$ kubectl create ns almost-empty
$ kubectl -n almost-empty create secret generic my-secret --from-literal=secret=value
```

3. Configure Contour to watch only the almost-empty namespace:

```bash
$ kubectl patch deployment contour -n projectcontour --type='json' -p='[{"op": "add", "path": "/spec/template/spec/containers/0/args/-", "value": "--watch-namespaces=almost-empty"}]'
```

4. Restart both Contour instances by scaling down and back up:
 
```bash
$ kubectl -n projectcontour scale deployment --replicas=0 contour
$ kubectl -n projectcontour scale deployment --replicas=2 contour
```

5. Verify that one Contour instance remains stuck in a non-ready state:

```bash
$ kubectl -n projectcontour get pod -l app=contour
NAME                      READY   STATUS    RESTARTS   AGE
contour-db59b775d-9k4wl   1/1     Running   0          4m17s
contour-db59b775d-tnqxm   0/1     Running   0          4m17s
```

The problem is a race condition, and its likelihood decreases if more resources (or no resources) are created in the watched namespace.

### PR DESCRIPTION
**Pull request by tsaarni**
This change will use polling for  `HasSynced()` call to align with how client-go's [`WaitForCacheSync()`](https://github.com/kubernetes/client-go/blob/690fd5274dfc971dcda653e45bc6e6852ab57316/tools/cache/shared_informer.go#L327-L343) operates. Previously it was only called when we received objects from the informer. By changing to polling, we prevent a race condition where Contour fails to recognize that the final object in the initial list has been received, which would prevent the xDS server from ever starting.

Fixes #6613 

## Details 

The startup of a follower instance depends on informers signaling that they have finished synchronizing resources with the API server. We use the [`SingleFileTracker`](https://github.com/projectcontour/contour/blob/f9b6f6fdfdd83d3639f6e8c55836401d749c19e1/internal/contour/handler.go#L63-L66) from client-go to track the processing of initial objects. This tracker increments when processing [starts](https://github.com/projectcontour/contour/blob/f9b6f6fdfdd83d3639f6e8c55836401d749c19e1/internal/contour/handler.go#L100) on a resource and decrements when its [finished](https://github.com/projectcontour/contour/blob/f9b6f6fdfdd83d3639f6e8c55836401d749c19e1/internal/contour/handler.go#L198). 

The [`HasSynced()`](https://github.com/projectcontour/contour/blob/f9b6f6fdfdd83d3639f6e8c55836401d749c19e1/internal/contour/handler.go#L202) method should ideally report synchronization status `true` right after [`Finished()`](https://github.com/projectcontour/contour/blob/f9b6f6fdfdd83d3639f6e8c55836401d749c19e1/internal/contour/handler.go#L198) is called for the last resource in the initial list (tracker reaches zero). However, in some cases it fails to report `true` immediately, causig the [boolean trigger](https://github.com/projectcontour/contour/blob/f9b6f6fdfdd83d3639f6e8c55836401d749c19e1/internal/contour/handler.go#L203) that starts the xDS server to never be set.

In case of a leader instance, an [extra update](https://github.com/projectcontour/contour/blob/f9b6f6fdfdd83d3639f6e8c55836401d749c19e1/internal/contour/handler.go#L123-L127) triggered by the leader selection itself has ensured that the xDS server starts.

### CODE REVIEW

**Comment by tsaarni** [comment]
Fix after test case failure. Coverage target is bit difficult to reach for this one.

File: internal/contour/handler.go [hunk 1]
```diff
@@ -146,19 +146,22 @@ func (e *EventHandler) Start(ctx context.Context) error {
 		// run to allow the holdoff timer to batch the updates from
 		// the API informers.
 		lastDAGRebuild = time.Now()
+
+		// initialSyncPollTimeout defines the duration to wait between polling attempts during the initial informer synchronization.
+		initialSyncPollTimeout = 100 * time.Millisecond
+
+		// initialSyncPollTimer is a timer set to trigger after the initialSyncPollTimeout duration.
+		initialSyncPollTimer = time.NewTimer(initialSyncPollTimeout)
```
Comment (sunjayBhatia) [inline internal/contour/handler.go:154]: do we want a Timer or a Ticker here?

Comment (tsaarni) [reply internal/contour/handler.go]: I switched to using `Ticker`, as it seems a bit more elegant.

With `Timer` I had to call `Reset()` to restart timer after each poll if synchronization was not completed yet. With `Ticker` I need to call `Stop()` after the final attempt.

**Review by sunjayBhatia — APPROVED** [review]
