### PR TITLE
test/e2e/upgrade: remove WaitForEnvoyDaemonSetOutOfDate check

### LINKED ISSUE #4647: upgrade test flakes after releasing v1.22.0
I've seen several (but not all) of the upgrade test runs fail after releasing v1.22.0. The failures can be seen at the top of https://github.com/projectcontour/contour/actions/workflows/prbuild.yaml. They all point to the code that waits for the Envoy DaemonSet to be out-of-date, and then updated. I'm wondering if the upgrade is a no-op so it never becomes out-of-date, though that doesn't explain why it still succeeds sometimes. Needs a little more digging into.

### PR DESCRIPTION
**Pull request by skriss**
Removes the check that the Envoy DaemonSet
has become out-of-date after the upgrade,
since during the time that we're waiting
for the Contour deployment to update, the
Envoy DS is likely to become up-to-date
again.

Closes #4647.

Signed-off-by: Steve Kriss <krisss@vmware.com>

### CODE REVIEW

File: test/e2e/deployment.go [hunk 1]
```diff
@@ -394,7 +380,8 @@ func (d *Deployment) waitForEnvoyDaemonSetUpdated() error {
 		if err := d.client.Get(context.TODO(), client.ObjectKeyFromObject(d.EnvoyDaemonSet), tempDS); err != nil {
 			return false, err
 		}
-		return tempDS.Status.NumberAvailable > 0 &&
+		return tempDS.Status.ObservedGeneration == tempDS.Generation &&
```
Comment (skriss) [inline test/e2e/deployment.go:383]: Added in the observed generation vs. generation check which I think should mostly prevent any race conditions here.

**Review by sunjayBhatia — APPROVED** [review]
