### PR TITLE
cmd/shutdownmanager: /shutdown handler fixes

### LINKED ISSUE #2896: Shutdown manager "error checking for file" log messages shouldn't be at ERROR level
After upgrading to Contour 0.8.1, I was surprised to find these entries in the `shutdown-manager` container logs:

```
envoy-m2trt shutdown-manager time="2020-09-10T02:11:58Z" level=error msg="error checking for file: stat /ok: no such file or directory" context=shutdownReadyHandler
envoy-m2trt shutdown-manager time="2020-09-10T02:11:59Z" level=error msg="error checking for file: stat /ok: no such file or directory" context=shutdownReadyHandler
envoy-m2trt shutdown-manager time="2020-09-10T02:12:00Z" level=error msg="error checking for file: stat /ok: no such file or directory" context=shutdownReadyHandler
envoy-m2trt shutdown-manager time="2020-09-10T02:12:01Z" level=error msg="error checking for file: stat /ok: no such file or directory" context=shutdownReadyHandler
```

My initial thought was that something was not configured correctly. But further investigation leads me to believe this is the normal behavior for the shutdown manager.

It polls a file continuously until it exists. Since it expects **not** to find it, I would argue errors from `os.Stat()` that relate to the file not existing are not to be logged at `level=error`, but rather `level=info`.

A minor detail for sure, but since we cannot see the pre stop hook logs from the Envoy side, it's best if normal things are reported as normal events from the `shutdown-manager` side.

Also, a final logging message with a confirmation that the file now exists would be nice.

### LINKED ISSUE #2897: ShutdownManager's /shutdown loop does not exit when client cancels request
The `/shutdown` handler in the `shutdown-manager` container has an infinite loop. If the HTTP client aborts the request and closes the connection, the goroutine performing that infinite loop will continue indefinitely (unless the the `/ok` file shows up).

I think the handler should use the `CloseNotifier` channel to exit if the client gives up:
https://golang.org/pkg/net/http/#CloseNotifier

This can be combined with the 1 second sleep.

This issue was discovered while investigating #2896 

**Environment:**
- Contour version: v1.8.1
- Kubernetes version: 1.17.1

### PR DESCRIPTION
**Pull request by bgagnon**
Fixes #2896 , fixes #2897 

- shutdownReady filepath ("/ok") is configurable
- os.Stat() interval is configurable
- detect client disconnection and stop check loop
- don't use error logging level when os.Stat() tells us the file does not yet exist
- add test coverage for success and client disconnect cases

### CODE REVIEW

File: cmd/contour/shutdownmanager.go [hunk 1]
```diff
@@ -98,17 +101,44 @@ func (s *shutdownmanagerContext) healthzHandler(w http.ResponseWriter, r *http.R
...
+		signalFilepath = s.shutdownReadyFile
+	} else {
+		signalFilepath = shutdownReadyFile
+	}
+	var signalFileCheckDuration time.Duration
+	if s.shutdownReadyCheckInterval != 0 {
+		signalFileCheckDuration = s.shutdownReadyCheckInterval
+	} else {
+		signalFileCheckDuration = shutdownReadyCheckInterval
+	}
```
Comment (bgagnon) [inline cmd/contour/shutdownmanager.go:117]: Not too happy with the location of this logic... maybe the defaults assignment should move to `newShutdownManagerContext()`.

File: cmd/contour/shutdownmanager.go [hunk 2]
```diff
@@ -38,14 +38,17 @@ const (
 
 // File path used in the /shutdown endpoint.
 const shutdownReadyFile = "/ok"
+const shutdownReadyCheckInterval = time.Second * 1
```
Comment (skriss) [inline cmd/contour/shutdownmanager.go:41]: nit: since we have a comment on the previous constant, it'd be nice to add one for this new const as well.

File: cmd/contour/shutdownmanager.go (hunk 1 above)
Comment (skriss) [reply cmd/contour/shutdownmanager.go:117]: Yeah, I'd probably assign the default values to these fields in `newShutdownManagerContext()`, then you can just override them as needed.

File: cmd/contour/shutdownmanager.go [hunk 3]
```diff
@@ -98,17 +101,44 @@ func (s *shutdownmanagerContext) healthzHandler(w http.ResponseWriter, r *http.R
...
+		signalFileCheckDuration = shutdownReadyCheckInterval
+	}
+
+	l := s.WithField("context", "shutdownReadyHandler")
+	ctx := r.Context()
 	for {
-		_, err := os.Stat(shutdownReadyFile)
-		if err != nil {
+		_, err := os.Stat(signalFilepath)
+		if err == nil {
```
Comment (skriss) [inline cmd/contour/shutdownmanager.go:123]: Not a huge deal, but I might reorder this to handle the error cases first, which is more common in go (I'd guess that not writing it that way in the first place contributed to the regression here) - so something like:

```go
if err != nil {
    if os.IsNotExist(err) {
        ...
    } else {
       ...
    }

    // wait & continue
}

// no error: ready for shutdown, write response
```

**Review by skriss — CHANGES_REQUESTED** [review]
thanks for the PR @bgagnon! I had a couple comments.

File: cmd/contour/shutdownmanager.go (hunk 1 above)
Comment (bgagnon) [reply cmd/contour/shutdownmanager.go]: Done!

File: cmd/contour/shutdownmanager.go (hunk 2 above)
Comment (bgagnon) [reply cmd/contour/shutdownmanager.go:43]: Done.

File: cmd/contour/shutdownmanager.go (hunk 3 above)
Comment (bgagnon) [reply cmd/contour/shutdownmanager.go]: Not exactly what you suggested, but I reordered the if cases.

**Review by youngnick — APPROVED** [review]
LGTM, great change, thanks @bgagnon

**Review by skriss — APPROVED** [review]
LGTM, thanks @bgagnon
