### PR TITLE
Upgrade Envoy go-control-plane and fix related changes to the spec

### LINKED ISSUE #2429: Upgrade go-control-plane
Should keep up to date with go-control-plane as new features are moved to the v3 API.

### PR DESCRIPTION
**Pull request by stevesloka**
Fixes #2429

Signed-off-by: Steve Sloka <slokas@vmware.com>

### CODE REVIEW

File: internal/contour/cluster.go [hunk 1]
```diff
@@ -17,8 +17,9 @@ import (
 	"sort"
 	"sync"
 
+	rsrc "github.com/envoyproxy/go-control-plane/pkg/resource/v2"
+
```
Comment (jpeach) [inline internal/contour/cluster.go:21]: Do we have a standard style for grouping imports?

File: internal/assert/assert.go [hunk 2]
```diff
@@ -55,6 +55,9 @@ func (a Assert) Equal(want, got interface{}) {
 }
 
 func unmarshalAny(a *any.Any) proto.Message {
+	if a == nil {
+		return nil
+	}
```
Comment (jpeach) [inline internal/assert/assert.go:60]: What happened here? Does this get a nil that it didn't get before?

File: internal/contour/cluster.go (hunk 1 above)
Comment (stevesloka) [reply internal/contour/cluster.go:21]: I don't know if we have a standard, I copied this from the go-control-plane code.

File: internal/assert/assert.go (hunk 2 above)
Comment (stevesloka) [reply internal/assert/assert.go:60]: This one was weird, after upgrading the deps, some tests started to fail. The error was the comparison was nil when checking. 

Maybe if you could put a set of eyes on it and see if something else jumps out at you.

Comment (jpeach) [reply internal/assert/assert.go:60]: I think that we just got lucky before. Any comparison involving an `any.Any` could have triggered this, since it makes `ptypes.Empty` return an error. Looks like ` RetryPolicyTypedConfig *any.Any` was added to a few types, which was probably one trigger.

File: internal/contour/cluster.go (hunk 1 above)
Comment (stevesloka) [reply internal/contour/cluster.go:21]: I renamed it to `resource`. I didn't think the other alias made sense.
