### PR TITLE
internal/dag: mirror cluster should create an Envoy cluster

### LINKED ISSUE #2557: Traffic mirroring does not work with Envoy host networking
Here's a very simple example I've copied from the docs:

```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: contour-internal
  namespace: some-namespace
spec:
  virtualhost:
    fqdn: some.internal.domain
  routes:
    - timeoutPolicy:
        response: 90s
      conditions:
        - prefix: /api/someapi
      services:
        - name: someservice
          port: 80
        - name: someservice-mirror
          port: 80
          mirror: true
```

The traffic is only received by `someservice`. I do not have an Envoy Service, instead I'm running my Envoy pods directly on hosts. I'm assuming this lack of service is the reason why mirroring does not work, since there are no complaints about this anywhere else. Any pointers for getting it to work?

- Contour version: 1.4.0 (had the same problem with 1.2.1)
- Kubernetes version: 1.16.8
- Cloud provider: AWS EKS
- OS: Amazon Linux 2

### LINKED ISSUE #2581: Envoy cluster not created for a service when mirror: true
This HTTPProxy def based on the mirroring example in the docs doesn't work
```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: podinfo-ingress
  namespace: mirror-test
spec:
  virtualhost:
    fqdn: some.public.domain
  routes:
    - conditions:
      - prefix: /
      services:
        - name: podinfo-331
          port: 9898
        - name: podinfo-331-mirror
          port: 9898
          mirror: true
```
The Pod serving `podinfo-331` responds to requests as expected
The Pod serving `podinfo-331-mirror` doesn't receive the requests

**Anything else you would like to add:**
The cluster for `podinfo-331-mirror` isn't created in envoy.
The `dynamic_route_configs` looks correct but the `mirror-test/podinfo-331-mirror/9898/da39a3ee5e` cluster is missing.
```
   "dynamic_route_configs": [
    {
     "version_info": "3",
     "route_config": {
      "@type": "type.googleapis.com/envoy.api.v2.RouteConfiguration",
      "name": "ingress_http",
      "virtual_hosts": [
       {
        "name": "some.public.domain",
        "domains": [
         "sr-test.customer-a.magnetic.io",
         "sr-test.customer-a.magnetic.io:*"
        ],
        "routes": [
         {
          "match": {
           "prefix": "/"
          },
          "route": {
           "cluster": "mirror-test/podinfo-331/9898/da39a3ee5e",
           "request_mirror_policies": [
            {
             "cluster": "mirror-test/podinfo-331-mirror/9898/da39a3ee5e"
            }
           ]
          }
         }
        ]
       }
      ],
      "request_headers_to_add": [
       {
        "header": {
         "key": "x-request-start",
         "value": "t=%START_TIME(%s.%3f)%"
        },
        "append": true
       }
      ]
     },
     "last_updated": "2020-06-12T22:29:25.688Z"
    }
   ]
```
```
service-stats::default_priority::max_connections::1024
service-stats::default_priority::max_pending_requests::1024
service-stats::default_priority::max_requests::1024
service-stats::default_priority::max_retries::3
service-stats::high_priority::max_connections::1024
service-stats::high_priority::max_pending_requests::1024
service-stats::high_priority::max_requests::1024
service-stats::high_priority::max_retries::3
service-stats::added_via_api::false
service-stats::127.0.0.1:9001::cx_active::1
service-stats::127.0.0.1:9001::cx_connect_fail::0
service-stats::127.0.0.1:9001::cx_total::1
service-stats::127.0.0.1:9001::rq_active::0
service-stats::127.0.0.1:9001::rq_error::0
service-stats::127.0.0.1:9001::rq_success::356
service-stats::127.0.0.1:9001::rq_timeout::0
service-stats::127.0.0.1:9001::rq_total::356
service-stats::127.0.0.1:9001::hostname::127.0.0.1
service-stats::127.0.0.1:9001::health_flags::healthy
service-stats::127.0.0.1:9001::weight::1
service-stats::127.0.0.1:9001::region::
service-stats::127.0.0.1:9001::zone::
service-stats::127.0.0.1:9001::sub_zone::
service-stats::127.0.0.1:9001::canary::false
service-stats::127.0.0.1:9001::priority::0
service-stats::127.0.0.1:9001::success_rate::-1.0
service-stats::127.0.0.1:9001::local_origin_success_rate::-1.0
mirror-test/podinfo-331/9898/da39a3ee5e::default_priority::max_connections::1024
mirror-test/podinfo-331/9898/da39a3ee5e::default_priority::max_pending_requests::1024
mirror-test/podinfo-331/9898/da39a3ee5e::default_priority::max_requests::1024
mirror-test/podinfo-331/9898/da39a3ee5e::default_priority::max_retries::3
mirror-test/podinfo-331/9898/da39a3ee5e::high_priority::max_connections::1024
mirror-test/podinfo-331/9898/da39a3ee5e::high_priority::max_pending_requests::1024
mirror-test/podinfo-331/9898/da39a3ee5e::high_priority::max_requests::1024
mirror-test/podinfo-331/9898/da39a3ee5e::high_priority::max_retries::3
mirror-test/podinfo-331/9898/da39a3ee5e::added_via_api::true
mirror-test/podinfo-331/9898/da39a3ee5e::10.20.0.22:9898::cx_active::0
mirror-test/podinfo-331/9898/da39a3ee5e::10.20.0.22:9898::cx_connect_fail::0
mirror-test/podinfo-331/9898/da39a3ee5e::10.20.0.22:9898::cx_total::1
mirror-test/podinfo-331/9898/da39a3ee5e::10.20.0.22:9898::rq_active::0
mirror-test/podinfo-331/9898/da39a3ee5e::10.20.0.22:9898::rq_error::0
mirror-test/podinfo-331/9898/da39a3ee5e::10.20.0.22:9898::rq_success::8
mirror-test/podinfo-331/9898/da39a3ee5e::10.20.0.22:9898::rq_timeout::0
mirror-test/podinfo-331/9898/da39a3ee5e::10.20.0.22:9898::rq_total::8
mirror-test/podinfo-331/9898/da39a3ee5e::10.20.0.22:9898::hostname::
mirror-test/podinfo-331/9898/da39a3ee5e::10.20.0.22:9898::health_flags::healthy
mirror-test/podinfo-331/9898/da39a3ee5e::10.20.0.22:9898::weight::1
mirror-test/podinfo-331/9898/da39a3ee5e::10.20.0.22:9898::region::
mirror-test/podinfo-331/9898/da39a3ee5e::10.20.0.22:9898::zone::
mirror-test/podinfo-331/9898/da39a3ee5e::10.20.0.22:9898::sub_zone::
mirror-test/podinfo-331/9898/da39a3ee5e::10.20.0.22:9898::canary::false
mirror-test/podinfo-331/9898/da39a3ee5e::10.20.0.22:9898::priority::0
mirror-test/podinfo-331/9898/da39a3ee5e::10.20.0.22:9898::success_rate::-1.0
mirror-test/podinfo-331/9898/da39a3ee5e::10.20.0.22:9898::local_origin_success_rate::-1.0
contour::default_priority::max_connections::100000
contour::default_priority::max_pending_requests::100000
contour::default_priority::max_requests::60000000
contour::default_priority::max_retries::50
contour::high_priority::max_connections::100000
contour::high_priority::max_pending_requests::100000
contour::high_priority::max_requests::60000000
contour::high_priority::max_retries::50
contour::added_via_api::false
contour::10.86.11.149:8001::cx_active::1
contour::10.86.11.149:8001::cx_connect_fail::7
contour::10.86.11.149:8001::cx_total::8
contour::10.86.11.149:8001::rq_active::4
contour::10.86.11.149:8001::rq_error::7
contour::10.86.11.149:8001::rq_success::0
contour::10.86.11.149:8001::rq_timeout::0
contour::10.86.11.149:8001::rq_total::5
contour::10.86.11.149:8001::hostname::contour
contour::10.86.11.149:8001::health_flags::healthy
contour::10.86.11.149:8001::weight::1
contour::10.86.11.149:8001::region::
contour::10.86.11.149:8001::zone::
contour::10.86.11.149:8001::sub_zone::
contour::10.86.11.149:8001::canary::false
contour::10.86.11.149:8001::priority::0
contour::10.86.11.149:8001::success_rate::-1.0
contour::10.86.11.149:8001::local_origin_success_rate::-1.0
```
As a workaround, adding an additional route that uses `podinfo-331-mirror` results in the `mirror-test/podinfo-331-mirror/9898/da39a3ee5e` cluster being created.
The mirroring then works as expected.
```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: podinfo-ingress
  namespace: mirror-test
spec:
  virtualhost:
    fqdn: some.public.domain
  routes:
    - conditions:
      - prefix: /
      services:
        - name: podinfo-331
          port: 9898
        - name: podinfo-331-mirror
          port: 9898
          mirror: true
    - conditions:
      - prefix: /
      - header:
          name: a-dummy-header
          exact: some-value-34a615f32e9a0c9e
      services:
        - name: podinfo-331-mirror
          port: 9898
```

**Environment:**
- Contour version: 1.5.0
- Kubernetes version: v1.14.10-gke.36
- Cloud provider: GKE

### PR DESCRIPTION
**Pull request by stevesloka**
Fixes #2581 
Fixes #2557 

When setting `mirror: true` on an `HTTPProxy` resource, the mirrored cluster was not getting created in Envoy which caused any traffic to the first cluster to not get mirrored properly to the "mirror" cluster. 

Signed-off-by: Steve Sloka <slokas@vmware.com>

### CODE REVIEW

File: internal/envoy/route.go [hunk 1]
```diff
@@ -249,10 +250,19 @@ func singleSimpleCluster(clusters []*dag.Cluster) bool {
...
-func weightedClusters(clusters []*dag.Cluster) *envoy_api_v2_route.WeightedCluster {
+func weightedClusters(clusters []*dag.Cluster, mirrorCluster *dag.MirrorPolicy) *envoy_api_v2_route.WeightedCluster {
 	var wc envoy_api_v2_route.WeightedCluster
 	var total uint32
 	for _, cluster := range clusters {
+		if mirrorCluster != nil {
+			// if the mirror cluster matches this cluster then skip since we don't want to
+			// route to this cluster, just allow it to be created in CDS
+			if mirrorCluster.Cluster != nil {
+				if cluster.Upstream.Name == mirrorCluster.Cluster.Upstream.Name {
```
Comment (jpeach) [inline internal/envoy/route.go:261]: Nit:
```Go
if mirrorCluster.Cluster != nil && mirrorCluster.Cluster.Upstream.Name == cluster.Upstream.Name {
        ...
}
```

File: internal/envoy/route.go [hunk 2]
```diff
@@ -249,10 +250,19 @@ func singleSimpleCluster(clusters []*dag.Cluster) bool {
...
 
 // weightedClusters returns a route.WeightedCluster for multiple services.
-func weightedClusters(clusters []*dag.Cluster) *envoy_api_v2_route.WeightedCluster {
+func weightedClusters(clusters []*dag.Cluster, mirrorCluster *dag.MirrorPolicy) *envoy_api_v2_route.WeightedCluster {
 	var wc envoy_api_v2_route.WeightedCluster
 	var total uint32
 	for _, cluster := range clusters {
+		if mirrorCluster != nil {
+			// if the mirror cluster matches this cluster then skip since we don't want to
+			// route to this cluster, just allow it to be created in CDS
```
Comment (jpeach) [inline internal/envoy/route.go:259]: Nit: comment sentences should be complete (capitalized and with a period) :)

File: internal/envoy/route.go [hunk 3]
```diff
@@ -269,12 +279,12 @@ func weightedClusters(clusters []*dag.Cluster) *envoy_api_v2_route.WeightedClust
...
 		wc.Clusters = append(wc.Clusters, c)
 	}
-	// Check if no weights were defined, if not default to even distribution
+	// Check if no weights were defined, default to even distribution
 	if total == 0 {
 		for _, c := range wc.Clusters {
 			c.Weight.Value = 1
 		}
-		total = uint32(len(clusters))
+		total = uint32(len(wc.Clusters))
```
Comment (jpeach) [inline internal/envoy/route.go:287]: So at this point, the mirrored Cluster is part of the slice. I don't think that it should be included in the slice to calculate weights.

File: internal/dag/builder.go [hunk 4]
```diff
@@ -778,9 +778,8 @@ func (b *Builder) computeRoutes(sw *ObjectStatusWriter, proxy *projcontour.HTTPP
 				r.MirrorPolicy = &MirrorPolicy{
 					Cluster: c,
 				}
-			} else {
-				r.Clusters = append(r.Clusters, c)
 			}
+			r.Clusters = append(r.Clusters, c)
```
Comment (jpeach) [inline internal/dag/builder.go:782]: I think that a better fix is to update `(*Route) Visit()` to visit the mirror policy as well as the direct route clusters. While you are there, could you also move it closer to the rest of the `Route` methods so that it's easier to find?

File: internal/envoy/route.go (hunk 1 above)
Comment (jpeach) [reply internal/envoy/route.go:261]: I think that this change is unnecessary once you update the route visitor.

File: internal/envoy/route.go (hunk 3 above)
Comment (stevesloka) [reply internal/envoy/route.go:287]: It's not part of the slice, any mirrored cluster never got added to `wc.Clusters` so not taken into the weight calculation.

File: internal/dag/builder.go (hunk 4 above)
Comment (stevesloka) [reply internal/dag/builder.go]: So I had a think about this and actually did this in the cluster visit. I was brute-forcing this by addressing it in the route visit, but really we needed this in the cluster.visit.

**Comment by stevesloka** [comment]
@jpeach can you take a look at this again?
