### PR TITLE
internal/envoy: fix no router filter crash

### LINKED ISSUE #4840: [Internal] Potential problem of listener.go#AddFilter
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

I am looking at the source code and making some private changes. Actually it is adding a custom http filter in 
[`internal\xdscache\v3\listener.go`](https://github.com/projectcontour/contour/blob/2ba1559ee5746c8616f6ec37f0905411f4bb03e4/internal/xdscache/v3/listener.go#L436) just like this:

```go
//...
cm := envoy_v3.HTTPConnectionManagerBuilder().
	Codec(envoy_v3.CodecForVersions(cfg.DefaultHTTPVersions...)).
	AddFilter(envoy_v3.FilterMisdirectedRequests(vh.VirtualHost.Name)).
        // Here is my custom filter, I add it here follow the FilterRewriteHostForCafe filter above
	AddFilter(envoy_v3.MyCustomHTTPFilter()).
	DefaultFilters().
	AddFilter(authFilter).
	RouteConfigName(path.Join("https", vh.VirtualHost.Name)).
//...
```

But got `Index out of range` exception when running (sorry I forget to capture the log but it's very easy to reproduce). The   exception was thrown from [`internal\envoy\v3\listener.go#AddFilter` ](https://github.com/projectcontour/contour/blob/2ba1559ee5746c8616f6ec37f0905411f4bb03e4/internal/envoy/v3/listener.go#L381) as follows:

```go

func (b *httpConnectionManagerBuilder) AddFilter(f *http.HttpFilter) *httpConnectionManagerBuilder {
	if f == nil {
		return b
	}

	b.filters = append(b.filters, f)

        // The first call of this function return directly without checking router filter, so it works well.
	if len(b.filters) == 1 {
		return b
	}

	lastIndex := len(b.filters) - 1
	routerIndex := -1
	for i, filter := range b.filters {
		if filter.GetTypedConfig().MessageIs(&envoy_extensions_filters_http_router_v3.Router{}) {
			routerIndex = i
			break
		}
	}

	if routerIndex != -1 && f.GetTypedConfig().MessageIs(&envoy_extensions_filters_http_router_v3.Router{}) {
		panic("Can't add more than one router to a filter chain")
	}

	if routerIndex != lastIndex {
                // Here we got an "index out of range" exception when the routerFilter is not found, because the routerIndex=-1
		routerFilter := b.filters[routerIndex]
		b.filters = append(b.filters[:routerIndex], b.filters[routerIndex+1])
		b.filters = append(b.filters, routerFilter)
	}

	return b
}

```

So if the router filter is not found, it will throw the exception. I found the router filter is added by `DefaultFilters()` function in [`internal\xdscache\v3\listener.go`](https://github.com/projectcontour/contour/blob/2ba1559ee5746c8616f6ec37f0905411f4bb03e4/internal/xdscache/v3/listener.go#L436). Which means the `AddFilter` function called before `DefaultFilter` won't find the router filter such that will throw an exception. But logically the `FilterMisdirectedRequests` is still OK because the first call of `AddFilter` doesn't check the router filter.

**What did you expect to happen:**
Maybe we should specify the order bethween `AddFilter` and `DefaultFilter`, or modify the `AddFilter` function to prevent this potential problem.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Contour version: latest
- Kubernetes version: (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by izturn**
Signed-off-by: Gang Liu <gang.liu@daocloud.io>

fix #4840

### CODE REVIEW

File: internal/envoy/v3/listener.go [hunk 1]
```diff
@@ -376,7 +376,7 @@ func (b *httpConnectionManagerBuilder) AddFilter(f *http.HttpFilter) *httpConnec
 		panic("Can't add more than one router to a filter chain")
 	}
 
-	if routerIndex != lastIndex {
+	if routerIndex != -1 && routerIndex != lastIndex {
```
Comment (sunjayBhatia) [inline internal/envoy/v3/listener.go:379]: could make line 375 `if routerIndex != -1 {` and have that if wrap that one and this one to make it so its a little less redundant

Comment (izturn) [reply internal/envoy/v3/listener.go]: done

**Review by sunjayBhatia — APPROVED** [review]
