### PR TITLE
internal/contour: enforce SNI name bindings

### LINKED ISSUE #2347: Contour does not enforce SNI host name bindings
**What steps did you take and what happened:**

Configure 2 proxies, `httpbin.jpeach.org` and `httpbin2.jpeach.org`. Make a SNI binding to one, but send the HTTP request to the other.

Envoy serves the correct certificate for the SNI name:

```
$ openssl s_client -connect 34.87.241.252:443 -servername httpbin-2.jpeach.org -showcerts | openssl x509 -noout -text -in -
depth=0 O = cert-manager
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 O = cert-manager
verify error:num=21:unable to verify the first certificate
verify return:1
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            32:28:20:39:af:55:4c:6a:b2:92:b8:e8:27:af:c4:c3
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: O = cert-manager
        Validity
            Not Before: Mar 17 03:44:45 2020 GMT
            Not After : Jun 15 03:44:45 2020 GMT
        Subject: O = cert-manager
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                RSA Public-Key: (2048 bit)
                Modulus:
                    00:d4:40:d0:11:83:99:9a:58:f7:80:bb:5e:9e:1d:
                    7e:e1:6d:75:bd:7a:2f:4b:6c:2e:64:ea:cc:63:01:
                    d1:07:1b:c5:bf:b4:3b:1c:d4:d1:03:02:3b:dc:db:
                    ed:59:a8:f2:b3:e0:a3:7d:2f:81:a1:20:08:13:b8:
                    a3:6a:e7:c7:8d:4e:b7:cd:2d:46:88:0c:fc:52:c6:
                    24:22:cb:44:6a:27:ab:ef:22:27:19:b3:68:28:2a:
                    67:6f:fc:b9:e8:03:db:f4:85:97:0c:bd:3f:62:b0:
                    88:7a:fd:f5:1d:d0:52:22:c0:cc:52:e7:b4:07:ef:
                    e0:5e:43:02:6c:21:2b:18:8b:ea:15:4c:95:c2:ee:
                    00:f6:b7:51:15:17:a7:a6:6b:1a:e4:c9:8a:60:40:
                    bf:3d:18:41:81:19:df:16:4c:cb:b2:62:bf:7b:e8:
                    b1:7a:ed:b6:9e:41:89:33:55:08:ba:4b:49:09:61:
                    ee:72:e9:07:73:b1:67:6d:89:d3:ea:05:b6:55:7f:
                    a8:07:d8:6f:98:a9:20:dd:30:c2:a0:c6:9c:07:cc:
                    c8:e3:6e:f6:9a:b1:79:ce:6d:02:d1:a7:e7:48:bb:
                    64:07:4c:16:39:72:62:67:49:f9:c4:ba:d1:b8:b9:
                    d9:f6:bb:28:0c:1f:a1:11:a9:9c:93:f3:a0:58:36:
                    22:9d
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
            X509v3 Extended Key Usage:
                TLS Web Server Authentication
            X509v3 Basic Constraints: critical
                CA:FALSE
            X509v3 Subject Alternative Name:
                DNS:httpbin-2.jpeach.org
    Signature Algorithm: sha256WithRSAEncryption
         39:ff:31:66:37:49:89:d1:28:1c:b8:68:4a:e9:27:03:71:03:
         98:35:0b:4a:48:02:a0:59:40:0d:84:c2:e8:77:82:3f:b6:48:
         0e:a8:c7:30:67:73:e2:59:cb:b6:32:58:31:91:c4:98:4f:3b:
         17:60:4f:3f:0a:46:02:8d:53:57:d9:c5:46:74:76:3d:fc:14:
         19:17:da:3e:9b:c8:69:1c:4f:ae:87:35:98:a3:38:5a:15:fe:
         7e:35:05:24:89:d9:9d:d1:a4:d2:9b:e4:f1:05:e3:5b:62:8d:
         60:d7:b3:0f:64:d7:10:25:5e:c4:ec:b9:31:21:58:37:bc:2e:
         3e:fd:6a:e2:25:4b:5f:a2:d5:7e:ec:d9:02:c4:6f:c3:9e:90:
         a7:d7:70:f6:32:88:2f:ac:09:01:85:ec:94:2f:7e:17:d3:27:
         f8:a5:01:19:a5:4c:74:2b:f0:ca:05:8a:6b:7e:b1:d4:0e:43:
         2a:e6:69:cc:36:4c:76:64:7d:9a:56:7c:88:70:42:1a:a4:1b:
         3b:60:32:bf:0e:50:80:f4:42:0d:4d:f1:f9:53:2a:5d:a0:47:
         ea:64:05:78:9f:c9:e5:e5:97:b9:ce:a7:1d:45:b8:bc:d0:8d:
         1a:15:2d:38:ec:9b:cb:1b:a3:77:2e:93:ff:0d:f0:63:a9:ae:
         64:4c:52:eb
```

But when we connect to a SNI name and use the Host header for a different name, we get a successful response:

```
$ curl --http1.1 --trace -  -k --resolve *:443:34.87.241.252 -H "Host: httpbin.jpeach.org" https://httpbin-2.jpeach.org/get
== Info: Added *:443:34.87.241.252 to DNS cache
== Info: RESOLVE *:443 is wildcard, enabling wildcard checks
== Info: Hostname httpbin-2.jpeach.org was found in DNS cache
== Info:   Trying 34.87.241.252...
== Info: TCP_NODELAY set
== Info: Connected to httpbin-2.jpeach.org (34.87.241.252) port 443 (#0)
== Info: ALPN, offering http/1.1
== Info: successfully set certificate verify locations:
== Info:   CAfile: /etc/ssl/cert.pem
  CApath: none
== Info: TLSv1.2 (OUT), TLS handshake, Client hello (1):
=> Send SSL data, 231 bytes (0xe7)
0000: 01 00 00 e3 03 03 aa f0 34 d6 84 71 f1 0d 3e 52 ........4..q..>R
0010: 44 2d 94 f8 16 ca e0 4a fc cf 3e 90 03 9a fb 04 D-.....J..>.....
0020: 47 03 71 0a 1c 0a 00 00 5c c0 30 c0 2c c0 28 c0 G.q.....\.0.,.(.
0030: 24 c0 14 c0 0a 00 9f 00 6b 00 39 cc a9 cc a8 cc $.......k.9.....
0040: aa ff 85 00 c4 00 88 00 81 00 9d 00 3d 00 35 00 ............=.5.
0050: c0 00 84 c0 2f c0 2b c0 27 c0 23 c0 13 c0 09 00 ..../.+.'.#.....
0060: 9e 00 67 00 33 00 be 00 45 00 9c 00 3c 00 2f 00 ..g.3...E...<./.
0070: ba 00 41 c0 11 c0 07 00 05 00 04 c0 12 c0 08 00 ..A.............
0080: 16 00 0a 00 ff 01 00 00 5e 00 00 00 19 00 17 00 ........^.......
0090: 00 14 68 74 74 70 62 69 6e 2d 32 2e 6a 70 65 61 ..httpbin-2.jpea
00a0: 63 68 2e 6f 72 67 00 0b 00 02 01 00 00 0a 00 08 ch.org..........
00b0: 00 06 00 1d 00 17 00 18 00 0d 00 1c 00 1a 06 01 ................
00c0: 06 03 ef ef 05 01 05 03 04 01 04 03 ee ee ed ed ................
00d0: 03 01 03 03 02 01 02 03 00 10 00 0b 00 09 08 68 ...............h
00e0: 74 74 70 2f 31 2e 31                            ttp/1.1
== Info: TLSv1.2 (IN), TLS handshake, Server hello (2):
<= Recv SSL data, 102 bytes (0x66)
0000: 02 00 00 62 03 03 5e 70 4a 0a 7c a4 17 59 93 55 ...b..^pJ.|..Y.U
0010: b0 d8 11 59 3b 2c 84 c2 c8 6a ab 51 97 6b 44 4f ...Y;,...j.Q.kDO
0020: 57 4e 47 52 44 01 20 8c e2 db ad 3c fe 9b 57 1e WNGRD. ....<..W.
0030: 42 2b d5 75 2f 8b 61 c5 66 50 92 a2 bb 71 05 79 B+.u/.a.fP...q.y
0040: bc 16 0e 1b 25 1b 56 cc a8 00 00 1a ff 01 00 01 ....%.V.........
0050: 00 00 0b 00 02 01 00 00 10 00 0b 00 09 08 68 74 ..............ht
0060: 74 70 2f 31 2e 31                               tp/1.1
== Info: TLSv1.2 (IN), TLS handshake, Certificate (11):
<= Recv SSL data, 796 bytes (0x31c)
0000: 0b 00 03 18 00 03 15 00 03 12 30 82 03 0e 30 82 ..........0...0.
0010: 01 f6 a0 03 02 01 02 02 10 32 28 20 39 af 55 4c .........2( 9.UL
0020: 6a b2 92 b8 e8 27 af c4 c3 30 0d 06 09 2a 86 48 j....'...0...*.H
0030: 86 f7 0d 01 01 0b 05 00 30 17 31 15 30 13 06 03 ........0.1.0...
0040: 55 04 0a 13 0c 63 65 72 74 2d 6d 61 6e 61 67 65 U....cert-manage
0050: 72 30 1e 17 0d 32 30 30 33 31 37 30 33 34 34 34 r0...20031703444
0060: 35 5a 17 0d 32 30 30 36 31 35 30 33 34 34 34 35 5Z..200615034445
0070: 5a 30 17 31 15 30 13 06 03 55 04 0a 13 0c 63 65 Z0.1.0...U....ce
0080: 72 74 2d 6d 61 6e 61 67 65 72 30 82 01 22 30 0d rt-manager0.."0.
0090: 06 09 2a 86 48 86 f7 0d 01 01 01 05 00 03 82 01 ..*.H...........
00a0: 0f 00 30 82 01 0a 02 82 01 01 00 d4 40 d0 11 83 ..0.........@...
00b0: 99 9a 58 f7 80 bb 5e 9e 1d 7e e1 6d 75 bd 7a 2f ..X...^..~.mu.z/
00c0: 4b 6c 2e 64 ea cc 63 01 d1 07 1b c5 bf b4 3b 1c Kl.d..c.......;.
00d0: d4 d1 03 02 3b dc db ed 59 a8 f2 b3 e0 a3 7d 2f ....;...Y.....}/
00e0: 81 a1 20 08 13 b8 a3 6a e7 c7 8d 4e b7 cd 2d 46 .. ....j...N..-F
00f0: 88 0c fc 52 c6 24 22 cb 44 6a 27 ab ef 22 27 19 ...R.$".Dj'.."'.
0100: b3 68 28 2a 67 6f fc b9 e8 03 db f4 85 97 0c bd .h(*go..........
0110: 3f 62 b0 88 7a fd f5 1d d0 52 22 c0 cc 52 e7 b4 ?b..z....R"..R..
0120: 07 ef e0 5e 43 02 6c 21 2b 18 8b ea 15 4c 95 c2 ...^C.l!+....L..
0130: ee 00 f6 b7 51 15 17 a7 a6 6b 1a e4 c9 8a 60 40 ....Q....k....`@
0140: bf 3d 18 41 81 19 df 16 4c cb b2 62 bf 7b e8 b1 .=.A....L..b.{..
0150: 7a ed b6 9e 41 89 33 55 08 ba 4b 49 09 61 ee 72 z...A.3U..KI.a.r
0160: e9 07 73 b1 67 6d 89 d3 ea 05 b6 55 7f a8 07 d8 ..s.gm.....U...
0170: 6f 98 a9 20 dd 30 c2 a0 c6 9c 07 cc c8 e3 6e f6 o.. .0........n.
0180: 9a b1 79 ce 6d 02 d1 a7 e7 48 bb 64 07 4c 16 39 ..y.m....H.d.L.9
0190: 72 62 67 49 f9 c4 ba d1 b8 b9 d9 f6 bb 28 0c 1f rbgI.........(..
01a0: a1 11 a9 9c 93 f3 a0 58 36 22 9d 02 03 01 00 01 .......X6"......
01b0: a3 56 30 54 30 0e 06 03 55 1d 0f 01 01 ff 04 04 .V0T0...U.......
01c0: 03 02 05 a0 30 13 06 03 55 1d 25 04 0c 30 0a 06 ....0...U.%..0..
01d0: 08 2b 06 01 05 05 07 03 01 30 0c 06 03 55 1d 13 .+.......0...U..
01e0: 01 01 ff 04 02 30 00 30 1f 06 03 55 1d 11 04 18 .....0.0...U....
01f0: 30 16 82 14 68 74 74 70 62 69 6e 2d 32 2e 6a 70 0...httpbin-2.jp
0200: 65 61 63 68 2e 6f 72 67 30 0d 06 09 2a 86 48 86 each.org0...*.H.
0210: f7 0d 01 01 0b 05 00 03 82 01 01 00 39 ff 31 66 ............9.1f
0220: 37 49 89 d1 28 1c b8 68 4a e9 27 03 71 03 98 35 7I..(..hJ.'.q..5
0230: 0b 4a 48 02 a0 59 40 0d 84 c2 e8 77 82 3f b6 48 .JH..Y@....w.?.H
0240: 0e a8 c7 30 67 73 e2 59 cb b6 32 58 31 91 c4 98 ...0gs.Y..2X1...
0250: 4f 3b 17 60 4f 3f 0a 46 02 8d 53 57 d9 c5 46 74 O;.`O?.F..SW..Ft
0260: 76 3d fc 14 19 17 da 3e 9b c8 69 1c 4f ae 87 35 v=.....>..i.O..5
0270: 98 a3 38 5a 15 fe 7e 35 05 24 89 d9 9d d1 a4 d2 ..8Z..~5.$......
0280: 9b e4 f1 05 e3 5b 62 8d 60 d7 b3 0f 64 d7 10 25 .....[b.`...d..%
0290: 5e c4 ec b9 31 21 58 37 bc 2e 3e fd 6a e2 25 4b ^...1!X7..>.j.%K
02a0: 5f a2 d5 7e ec d9 02 c4 6f c3 9e 90 a7 d7 70 f6 _..~....o.....p.
02b0: 32 88 2f ac 09 01 85 ec 94 2f 7e 17 d3 27 f8 a5 2./....../~..'..
02c0: 01 19 a5 4c 74 2b f0 ca 05 8a 6b 7e b1 d4 0e 43 ...Lt+....k~...C
02d0: 2a e6 69 cc 36 4c 76 64 7d 9a 56 7c 88 70 42 1a *.i.6Lvd}.V|.pB.
02e0: a4 1b 3b 60 32 bf 0e 50 80 f4 42 0d 4d f1 f9 53 ..;`2..P..B.M..S
02f0: 2a 5d a0 47 ea 64 05 78 9f c9 e5 e5 97 b9 ce a7 *].G.d.x........
0300: 1d 45 b8 bc d0 8d 1a 15 2d 38 ec 9b cb 1b a3 77 .E......-8.....w
0310: 2e 93 ff 0d f0 63 a9 ae 64 4c 52 eb             .....c..dLR.
== Info: TLSv1.2 (IN), TLS handshake, Server key exchange (12):
<= Recv SSL data, 300 bytes (0x12c)
0000: 0c 00 01 28 03 00 1d 20 44 0d 6e 02 67 b7 f3 46 ...(... D.n.g..F
0010: 6b 67 85 7e 0d cf 55 af 86 2b 44 1b d2 5a 26 40 kg.~..U..+D..Z&@
0020: 15 4a 2d 84 ba d9 94 23 04 01 01 00 46 5c 35 52 .J-....#....F\5R
0030: a2 c6 cb a8 68 e6 3b ac e6 57 bb 91 a8 e0 2d b5 ....h.;..W....-.
0040: df 3d 2a 0c c8 3a c5 85 89 dc 0b b2 f3 d5 62 4c .=*..:........bL
0050: 32 61 16 fe 1c 88 ac be f1 74 0f e4 6d 3f 48 09 2a.......t..m?H.
0060: ce b2 7b 20 48 8c 01 b3 08 f0 2e e1 e3 55 3e c8 ..{ H........U>.
0070: e2 e0 28 65 a1 e7 34 eb 18 85 c8 fb ad 53 6a 9a ..(e..4......Sj.
0080: d6 36 ff c4 f9 ed d4 8c ad f2 24 64 e1 69 27 7f .6........$d.i'
0090: 11 77 1e f5 60 33 d5 34 7d 49 3a 93 9c 4b 32 e0 .w..`3.4}I:..K2.
00a0: a3 c1 21 7a ee f1 70 6c 50 3b b0 ec 5c 29 b9 a8 ..!z..plP;..\)..
00b0: b9 d6 41 1c 99 fa 2c 0e 51 67 93 b0 1d b1 8f ff ..A...,.Qg......
00c0: b7 ca 37 04 38 47 8f 84 d9 63 aa fd 34 a8 47 72 ..7.8G...c..4.Gr
00d0: 90 63 e9 28 97 73 4f 5e ed e4 2b f3 96 c5 66 0c .c.(.sO^..+...f.
00e0: fe 29 55 66 73 d5 5f 98 b5 52 b9 e4 a7 12 88 56 .)Ufs._..R.....V
00f0: cc 06 62 ac df 9d 67 8e d2 a5 c2 74 2a c5 3d c4 ..b...g....t*.=.
0100: be cd 11 7b b3 44 be e1 d4 6d 94 ea 92 71 dd 2b ...{.D...m...q.+
0110: 4d ad 40 c4 48 74 de 8c b1 55 70 8b e8 97 fb e3 M.@.Ht...Up.....
0120: d8 b4 35 a2 f1 39 a1 07 29 be f8 49             ..5..9..)..I
== Info: TLSv1.2 (IN), TLS handshake, Server finished (14):
<= Recv SSL data, 4 bytes (0x4)
0000: 0e 00 00 00                                     ....
== Info: TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
=> Send SSL data, 37 bytes (0x25)
0000: 10 00 00 21 20 38 ef e3 a0 62 55 ce b6 f1 97 2e ...! 8...bU.....
0010: fe 1f 8a 1c e7 14 76 31 f2 08 ab 4a a3 cb 34 dd ......v1...J..4.
0020: 83 0c 57 dd 75                                  ..W.u
== Info: TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
=> Send SSL data, 1 bytes (0x1)
0000: 01                                              .
== Info: TLSv1.2 (OUT), TLS handshake, Finished (20):
=> Send SSL data, 16 bytes (0x10)
0000: 14 00 00 0c af bc 4b 39 3b 68 74 db 0c ec a6 a2 ......K9;ht.....
== Info: TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
<= Recv SSL data, 1 bytes (0x1)
0000: 01                                              .
== Info: TLSv1.2 (IN), TLS handshake, Finished (20):
<= Recv SSL data, 16 bytes (0x10)
0000: 14 00 00 0c 51 93 9d dd ce 92 1a 7d dd 76 b7 a4 ....Q......}.v..
== Info: SSL connection using TLSv1.2 / ECDHE-RSA-CHACHA20-POLY1305
== Info: ALPN, server accepted to use http/1.1
== Info: Server certificate:
== Info:  subject: O=cert-manager
== Info:  start date: Mar 17 03:44:45 2020 GMT
== Info:  expire date: Jun 15 03:44:45 2020 GMT
== Info:  issuer: O=cert-manager
== Info:  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
=> Send header, 85 bytes (0x55)
0000: 47 45 54 20 2f 67 65 74 20 48 54 54 50 2f 31 2e GET /get HTTP/1.
0010: 31 0d 0a 48 6f 73 74 3a 20 68 74 74 70 62 69 6e 1..Host: httpbin
0020: 2e 6a 70 65 61 63 68 2e 6f 72 67 0d 0a 55 73 65 .jpeach.org..Use
0030: 72 2d 41 67 65 6e 74 3a 20 63 75 72 6c 2f 37 2e r-Agent: curl/7.
0040: 36 34 2e 31 0d 0a 41 63 63 65 70 74 3a 20 2a 2f 64.1..Accept: */
0050: 2a 0d 0a 0d 0a                                  *....
<= Recv header, 17 bytes (0x11)
0000: 48 54 54 50 2f 31 2e 31 20 32 30 30 20 4f 4b 0d HTTP/1.1 200 OK.
0010: 0a                                              .
<= Recv header, 15 bytes (0xf)
0000: 73 65 72 76 65 72 3a 20 65 6e 76 6f 79 0d 0a    server: envoy..
<= Recv header, 37 bytes (0x25)
0000: 64 61 74 65 3a 20 54 75 65 2c 20 31 37 20 4d 61 date: Tue, 17 Ma
0010: 72 20 32 30 32 30 20 30 33 3a 35 34 3a 35 30 20 r 2020 03:54:50
0020: 47 4d 54 0d 0a                                  GMT..
<= Recv header, 32 bytes (0x20)
0000: 63 6f 6e 74 65 6e 74 2d 74 79 70 65 3a 20 61 70 content-type: ap
0010: 70 6c 69 63 61 74 69 6f 6e 2f 6a 73 6f 6e 0d 0a plication/json..
<= Recv header, 21 bytes (0x15)
0000: 63 6f 6e 74 65 6e 74 2d 6c 65 6e 67 74 68 3a 20 content-length:
0010: 33 33 31 0d 0a                                  331..
<= Recv header, 32 bytes (0x20)
0000: 61 63 63 65 73 73 2d 63 6f 6e 74 72 6f 6c 2d 61 access-control-a
0010: 6c 6c 6f 77 2d 6f 72 69 67 69 6e 3a 20 2a 0d 0a llow-origin: *..
<= Recv header, 40 bytes (0x28)
0000: 61 63 63 65 73 73 2d 63 6f 6e 74 72 6f 6c 2d 61 access-control-a
0010: 6c 6c 6f 77 2d 63 72 65 64 65 6e 74 69 61 6c 73 llow-credentials
0020: 3a 20 74 72 75 65 0d 0a                         : true..
<= Recv header, 34 bytes (0x22)
0000: 78 2d 65 6e 76 6f 79 2d 75 70 73 74 72 65 61 6d x-envoy-upstream
0010: 2d 73 65 72 76 69 63 65 2d 74 69 6d 65 3a 20 32 -service-time: 2
0020: 0d 0a                                           ..
<= Recv header, 2 bytes (0x2)
0000: 0d 0a                                           ..
<= Recv data, 331 bytes (0x14b)
0000: 7b 0a 20 20 22 61 72 67 73 22 3a 20 7b 7d 2c 20 {.  "args": {},
0010: 0a 20 20 22 68 65 61 64 65 72 73 22 3a 20 7b 0a .  "headers": {.
0020: 20 20 20 20 22 41 63 63 65 70 74 22 3a 20 22 2a     "Accept": "*
0030: 2f 2a 22 2c 20 0a 20 20 20 20 22 43 6f 6e 74 65 /*", .    "Conte
0040: 6e 74 2d 4c 65 6e 67 74 68 22 3a 20 22 30 22 2c nt-Length": "0",
0050: 20 0a 20 20 20 20 22 48 6f 73 74 22 3a 20 22 68  .    "Host": "h
0060: 74 74 70 62 69 6e 2e 6a 70 65 61 63 68 2e 6f 72 ttpbin.jpeach.or
0070: 67 22 2c 20 0a 20 20 20 20 22 55 73 65 72 2d 41 g", .    "User-A
0080: 67 65 6e 74 22 3a 20 22 63 75 72 6c 2f 37 2e 36 gent": "curl/7.6
0090: 34 2e 31 22 2c 20 0a 20 20 20 20 22 58 2d 45 6e 4.1", .    "X-En
00a0: 76 6f 79 2d 45 78 70 65 63 74 65 64 2d 52 71 2d voy-Expected-Rq-
00b0: 54 69 6d 65 6f 75 74 2d 4d 73 22 3a 20 22 31 35 Timeout-Ms": "15
00c0: 30 30 30 22 2c 20 0a 20 20 20 20 22 58 2d 45 6e 000", .    "X-En
00d0: 76 6f 79 2d 45 78 74 65 72 6e 61 6c 2d 41 64 64 voy-External-Add
00e0: 72 65 73 73 22 3a 20 22 32 30 33 2e 32 32 30 2e ress": "203.220.
00f0: 32 31 32 2e 32 34 37 22 0a 20 20 7d 2c 20 0a 20 212.247".  }, .
0100: 20 22 6f 72 69 67 69 6e 22 3a 20 22 32 30 33 2e  "origin": "203.
0110: 32 32 30 2e 32 31 32 2e 32 34 37 22 2c 20 0a 20 220.212.247", .
0120: 20 22 75 72 6c 22 3a 20 22 68 74 74 70 73 3a 2f  "url": "https:/
0130: 2f 68 74 74 70 62 69 6e 2e 6a 70 65 61 63 68 2e /httpbin.jpeach.
0140: 6f 72 67 2f 67 65 74 22 0a 7d 0a                org/get".}.
{
  "args": {},
  "headers": {
    "Accept": "*/*",
    "Content-Length": "0",
    "Host": "httpbin.jpeach.org",
    "User-Agent": "curl/7.64.1",
    "X-Envoy-Expected-Rq-Timeout-Ms": "15000",
    "X-Envoy-External-Address": "203.220.212.247"
  },
  "origin": "203.220.212.247",
  "url": "https://httpbin.jpeach.org/get"
}
== Info: Connection #0 to host httpbin-2.jpeach.org left intact
* Closing connection 0
```

**What did you expect to happen:**

Contour should have programed Envoy to enforce the correspondence between SNI name and virtual host.

**Anything else you would like to add:**

Binding the server name is best practice per [RFC 6066](https://tools.ietf.org/html/rfc6066#section-11.1):

>    Since it is possible for a client to present a different server_name
   in the application protocol, application server implementations that
   rely upon these names being the same MUST check to make sure the
   client did not present a different name in the application protocol.

**Environment:**

- Contour version: 1.2.1

### PR DESCRIPTION
**Pull request by jpeach**
reviously, Contour generates a single RouteConfiguration named
`ingress_https` that contained all the virtual hosts that were being
served over HTTPS. This meant that if the client request SNI name "A",
it could send a HTTP request for virtual host "B" and it would work.
This behaviour is generally unexpected and can violate security invariants
that we want to enforce, e.g. protecting virtual hosts with client
certificate validation.

The fix is to generate a unique route configuration for each virtual host
and match them to each unique SNI name. This means that once the SNI name
is matched, all the routes from the attached route aonfiguration belong
to the same virtual host. This enforces a one to one correspondence
between SNI names and virtual hosts.

After this, the well-known "ingress_https" route configuration no longer
exists, except for TCP proxying.

This fixes #2347.

Signed-off-by: James Peach <jpeach@vmware.com>

### CODE REVIEW

**Comment by jpeach** [comment]
Needs a rebase once #2379 is merged. Looking at where to add documentation.

**Comment by jpeach** [comment]
On Mar 26, 2020, at 3:06 AM, Steve Sloka <notifications@github.com> wrote:

Seems like you are stacking PRs. The work in #2379<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fprojectcontour%2Fcontour%2Fpull%2F2379&data=02%7C01%7Cjpeach%40vmware.com%7C11b85ad1928d4f4e784c08d7d0d667d4%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637207491597103107&sdata=GNklisUN8tneZaAg%2BCaqpEtoRyf0u9h3hRuEPTrSsD0%3D&reserved=0> is included in this PR it seems.


Yes, I need that chance here for fixing tests. Once it lands I can rebase it away.

**Comment by jpeach** [comment]
Added documentation. Ready for review once #2379 lands and I rebase.

**Comment by jpeach** [comment]
Rebased and ready for review.

File: internal/envoy/listener.go [hunk 1]
```diff
@@ -65,64 +65,129 @@ func Listener(name, address string, port int, lf []*envoy_api_v2_listener.Listen
 	return l
 }
 
-// HTTPConnectionManager creates a new HTTP Connection Manager filter
-// for the supplied route, access log, and client request timeout.
-func HTTPConnectionManager(routename string, accesslogger []*accesslog.AccessLog, requestTimeout time.Duration) *envoy_api_v2_listener.Filter {
+type httpConnectionManagerBuilder struct {
```
Comment (youngnick) [inline internal/envoy/listener.go]: This is really nice, reads very well.
